api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    error_formats:
        jsonld: ["application/ld+json"] # Hydra error formats
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
       
