lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    token_extractors:
        cookie:
            enabled: true
            name:    AUTH_TOKEN
        authorization_header:
            enabled: false   # on désactive pour forcer l'usage cookie
        query_parameter:
            enabled: false
