nelmio_cors:
    defaults:
        origin_regex: true
        # Utilise la variable d'environnement CORS_ALLOW_ORIGIN
        # Format: liste séparée par des virgules (ex: http://localhost:3000,http://127.0.0.1:3000)
        allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Authorization', 'Content-Type']
        max_age: 3600
    paths:
        '^/api': 
            allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
            allow_credentials: true
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
