nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000']
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Authorization', 'Content-Type']
        max_age: 3600
        forced_allow_origin_value: 'http://localhost:3000'
    paths:
        '^/api': 
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
